version: '3'
services:
  nginx:
    build: ./config/nginx
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx/nginx:/etc/nginx.conf.d
    image: 11thbackend/nginx:latest
    depends_on:
      - web
    platform: linux/amd64
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 hackathon.wsgi:application
    volumes:
      - .:/code #현재 호스트의 작업 디렉토리를 컨테이너 내부의 /code 로 마운팅 한다는 뜻
    ports:
      - "8000:8000"
    platform: linux/amd64
    image: 11thbackend/web:latest
    environment:
      - DJANGO_SETTINGS_MODULE=hackathon.settings.prod